spring.data.mongodb.uri=mongodb+srv://deepakkr7975_db_user:SEMvcv0XoY7T9QJ6@cluster0.xqmdj5v.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true